### ISSUE TITLE
Updating README install information

### ISSUE THREAD

**Issue by alisonlhart** [redhat-cop/edge.microshift#55]
This section https://github.com/redhat-cop/edge.microshift#installing in the README needs to be updated with the correct install information. 

Since the collection is now on Automation Hub, instead of installing from `ansible-galaxy collection install git+https://github.com/redhat-cop/edge.microshift`, install directly with the collection name: `ansible-galaxy collection install edge.microshift`. 

Any other install references (if relevant) should be updated in the same way. 

If there is no upcoming release planned to Automation Hub, please make a one-off minor release for this fix, so customers can receive the updated docs as soon as possible.

**Comment by resoluteCoder** [comment]
Updated and pushed to automation hub
